# Generated by Django 5.1.15 on 2026-07-19 02:35

import apps.averias.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Averia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('area', models.CharField(choices=[('COCINA', 'Cocina'), ('BANO', 'Baño'), ('SALA', 'Sala'), ('DORMITORIO', 'Dormitorio'), ('EXTERIOR', 'Área exterior'), ('OTRO', 'Otro')], max_length=12, verbose_name='área afectada')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REPARACION', 'En reparación'), ('SOLUCIONADO', 'Solucionado')], default='PENDIENTE', max_length=15, verbose_name='estado')),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='gasto de reparación')),
                ('notas_admin', models.TextField(blank=True, verbose_name='notas del administrador')),
                ('fecha_solucion', models.DateField(blank=True, null=True, verbose_name='fecha de solución')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='averias', to='apartamentos.apartamento', verbose_name='apartamento')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='averias_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='atendida por')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='averias', to=settings.AUTH_USER_MODEL, verbose_name='inquilino')),
            ],
            options={
                'verbose_name': 'avería',
                'verbose_name_plural': 'averías',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FotoAveria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('imagen', models.FileField(upload_to=apps.averias.models.ruta_foto_averia, verbose_name='imagen')),
                ('averia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='averias.averia', verbose_name='avería')),
            ],
            options={
                'verbose_name': 'foto de avería',
                'verbose_name_plural': 'fotos de avería',
            },
        ),
    ]
