# Generated by Django 5.1.15 on 2026-07-18 18:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('porcentaje_multa', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Porcentaje aplicado sobre el saldo pendiente al vencer (RF-007).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='porcentaje de multa por morosidad')),
                ('monto_multa_fijo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Si es mayor que 0, se usa en lugar del porcentaje.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monto fijo de multa')),
                ('dias_anticipacion_recordatorio', models.PositiveIntegerField(default=3, help_text='Días antes del vencimiento para enviar el recordatorio (RF-010).', verbose_name='días de anticipación del recordatorio')),
                ('nombre_empresa', models.CharField(default='VATISHE S.R.L.', max_length=150, verbose_name='nombre de la empresa')),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuración del sistema',
            },
        ),
        migrations.CreateModel(
            name='RegistroCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tipo', models.CharField(choices=[('RECORDATORIO', 'Recordatorio de pago'), ('COMP_RECHAZADO', 'Comprobante rechazado'), ('AVERIA_ACT', 'Avería actualizada')], max_length=20, verbose_name='tipo')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='destinatario')),
                ('asunto', models.CharField(max_length=255, verbose_name='asunto')),
                ('clave_unicidad', models.CharField(blank=True, max_length=120, verbose_name='clave de unicidad')),
                ('exitoso', models.BooleanField(default=True, verbose_name='enviado con éxito')),
                ('detalle_error', models.TextField(blank=True, verbose_name='detalle de error')),
            ],
            options={
                'verbose_name': 'registro de correo',
                'verbose_name_plural': 'registros de correo',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tipo', 'clave_unicidad'], name='core_regist_tipo_b750c4_idx')],
            },
        ),
    ]
