# Generated by Django 5.1.15 on 2026-07-18 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(help_text='Identificador visible del apartamento, p. ej. «Apto. 101».', max_length=40, unique=True, verbose_name='número/nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto mensual')),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que vence el cobro (se ajusta si el mes es más corto).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día de vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'apartamento',
                'verbose_name_plural': 'apartamentos',
                'ordering': ['codigo'],
            },
        ),
    ]
