# Generated by Django 5.1.15 on 2026-07-18 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('anio', models.PositiveIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='mes')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto base')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADO', 'Pagado'), ('CON_MULTA', 'Con multa')], default='PENDIENTE', max_length=12, verbose_name='estado')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='apartamentos.apartamento', verbose_name='apartamento')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='contratos.contrato', verbose_name='contrato')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to=settings.AUTH_USER_MODEL, verbose_name='inquilino')),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
                'ordering': ['-anio', '-mes', 'apartamento__codigo'],
                'constraints': [models.UniqueConstraint(fields=('apartamento', 'anio', 'mes'), name='un_cobro_por_apartamento_y_periodo')],
            },
        ),
    ]
