# Generated by Django 5.1.15 on 2026-07-19 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='porcentaje aplicado')),
                ('motivo', models.CharField(default='Morosidad', max_length=120, verbose_name='motivo')),
                ('fecha_aplicacion', models.DateField(verbose_name='fecha de aplicación')),
                ('exonerada', models.BooleanField(default=False, verbose_name='exonerada')),
                ('motivo_exoneracion', models.TextField(blank=True, verbose_name='motivo de exoneración')),
                ('exonerada_en', models.DateTimeField(blank=True, null=True, verbose_name='exonerada en')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='cobros.cobro', verbose_name='cobro')),
                ('exonerada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_exoneradas', to=settings.AUTH_USER_MODEL, verbose_name='exonerada por')),
            ],
            options={
                'verbose_name': 'multa',
                'verbose_name_plural': 'multas',
                'ordering': ['-fecha_aplicacion', '-creado_en'],
            },
        ),
    ]
