# Generated by Django 5.1.15 on 2026-07-18 20:13

import apps.pagos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('fecha', models.DateField(verbose_name='fecha del pago')),
                ('metodo', models.CharField(choices=[('SINPE', 'SINPE Móvil'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Depósito')], max_length=15, verbose_name='método')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('comprobante', models.FileField(upload_to=apps.pagos.models.ruta_comprobante, verbose_name='comprobante')),
                ('estado_verificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='estado de verificación')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='motivo de rechazo')),
                ('verificado_en', models.DateTimeField(blank=True, null=True, verbose_name='verificado en')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='cobros.cobro', verbose_name='cobro')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_verificados', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
            ],
            options={
                'verbose_name': 'abono',
                'verbose_name_plural': 'abonos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
