# Generated by Django 5.1.15 on 2026-07-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto mensual')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='apartamentos.apartamento', verbose_name='apartamento')),
                ('inquilino', models.ForeignKey(limit_choices_to={'rol': 'INQUILINO'}, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to=settings.AUTH_USER_MODEL, verbose_name='inquilino')),
                ('renovacion_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='contratos.contrato', verbose_name='renovación de')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('apartamento',), name='un_contrato_activo_por_apartamento')],
            },
        ),
    ]
